version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - STORE_API_KEY=${STORE_API_KEY}
      - LLM_API_KEY=${LLM_API_KEY}
      - STORE_BASE_URL=${STORE_BASE_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3